# command for SE510 platform with MIPS core
# make ARCH=mips CROSS_COMPILE=mipsel-linux- -C /media/a003257/2TB/avm/se510/AVerCasterHDDuet/RT288x_SDK/source/linux-2.6.21.x M=/home/a003257/workspace/notes/tmp/hello modules

obj-m := hello.o
